BUFFER_SECONDS = 7
TEST_MODE = True
CONFIRM_MATCH_SECONDS = 15 if TEST_MODE else 60
WAIT_SECONDS = 55 if TEST_MODE else 60*20
ASSUME_INACTIVE_DAYS = 60 # 30 day persistent login + 30 days
MIN_BETWEEN_R_EM = 20
CONTACT_EMAIL = "empathyspot@gmail.com"
URL_WITH_ALT = "https://empathychat.anvil.app" #"https://www.empathyspot.org (or https://minty-sarcastic-telephone.anvil.app )"
URL = "https://empathychat.anvil.app" #"https://www.empathyspot.org"
SELECTED_TAB_COLOR = "theme:White"
NONSELECTED_TAB_COLOR = "theme:Gray 200"
START_EARLY_MINUTES = 5
