BUFFER_SECONDS = 7
CONFIRM_MATCH_SECONDS = 15 #60
WAIT_SECONDS = 55 #60*20
ASSUME_INACTIVE_DAYS = 60 #30 day persistent login + 30 days
MIN_BETWEEN_R_EM = 20
CONTACT_EMAIL = "empathyspot@gmail.com"
URL_WITH_ALT = "https://www.empathyspot.org (or https://minty-sarcastic-telephone.anvil.app )"
URL = "https://www.empathyspot.org"
SELECTED_TAB_COLOR = "theme:White"
NONSELECTED_TAB_COLOR = "theme:Gray 200"
