BUFFER_SECONDS = 7
CONFIRM_MATCH_SECONDS = 60 #15
WAIT_SECONDS = 60*20 #55
ASSUME_INACTIVE_DAYS = 60 # 30 day persistent login + 30 days
MIN_BETWEEN_R_EM = 20
CONTACT_EMAIL = "empathyspot@gmail.com"
URL_WITH_ALT = "https://e6hfysk4hhri7btc.anvil.app/FEJAOY5Q5ZBKEJWWCKZNNCJZ" #"https://www.empathyspot.org (or https://minty-sarcastic-telephone.anvil.app )"
URL = "https://e6hfysk4hhri7btc.anvil.app/FEJAOY5Q5ZBKEJWWCKZNNCJZ" #"https://www.empathyspot.org"
SELECTED_TAB_COLOR = "theme:White"
NONSELECTED_TAB_COLOR = "theme:Gray 200"
START_EARLY_MINUTES = 5
