unique_ids:
  forms: {MenuForm: LQALZEBVWCAROGHACHPLSBCRXDO4OOBO, MenuForm.ConnectionsMenu.Connections: LL7KYXL4BXNM3S3HJCAHGVQBOTDUB55K,
    MenuForm.DashForm.ProposalRowTemplate: FFDCGOSM4EZON7VB6JSZ2C7OM2MZYMFL, MenuForm.MyGroupsForm: OS7WXWWX7LHOBNF7KXSZ3QYHM75U66U7,
    MenuForm.GroupsMenu.Groups: 3D7EYITMORPXBJPK24O5GTEAX4MWVPER, MenuForm.WaitForm.TimerForm: 22XNYB3NGYU6HSTKNTX6IJU5WN7U5SQO,
    MenuForm.DashForm: EHZXWVWKJQF4YZIUG5LOWMVHL5UIDUMK, MenuForm.SettingsForm: LUQMPWU73DALOFU2FL23UFHAVVTKBLUX,
    LoginForm: U2WRVYCDWTTZ75XOUG5L2YOX2IJKMC57, MenuForm.MatchForm.MyJitsi: C77GZPNO7ZX3C7KXFKFUX3QCMP4WOHIK,
    RowTemplate1: H6TFH5H42VOJPYUECJQ5IYJQPOW3C7J4, MenuForm.DashForm.CreateForm: FQPF4AUYI6C3RES67N43E3MRNGSYLTGL,
    MenuForm.GroupsMenu: BCPTFFZUQDJYWWQGDZ7JN3UHRXECRQN2, MenuForm.ConnectionsMenu.Connections.ConnectionRow: 4N2DTNZQ6SNQCDWYT7DBL2C77B4A7UG5,
    MenuForm.MatchForm: L6XPKZSV2CGX5N6OQ553T5VUSP75I267, MenuForm.HorizontalRule: 3KHHBDA25PB4SUKZLCQVNBFODCLQAT4K,
    MenuForm.MatchForm.ChatTemplate: CIODZUWNBDQ7GOKRBKNIH5T43Y4UMEM2, MenuForm.ConnectionsMenu.Blocks: 4V2CC3CY6V7FU27DBZWSDZT5UOMVDXNP,
    MenuForm.ConnectionsMenu: N72A3754IWYEWKHSRB56XYWGL2NWXSJX, MenuForm.WaitForm: OSIDM6JSG7C65N2DFVSUMY33DDU5IITC,
    MenuForm.DashForm.CreateForm.TimeProposalTemplate: MAXX7CACIATD6Z3K7F4IENDZVJIT3YS4,
    MenuForm.GroupsMenu.Members: YAKCFP37GREYLYZQ247LONPV2SRKLZCL}
  modules: {helper: B22GXONONXNAFNSHVMP6RMTVPMUS7WAL, parameters: QEXYSHPVRD5JQHPZUUBUVGV6IDOTQW3W}
  server_modules: {matcher: W7L6AF2SOAIOBVHDEMYQSPJP63FLSBB5, server_misc: JRRRPOMXAEI6QJMQOIQUBZN5PKXZLCVB,
    testserver: WNXC4JO5QXE6UA7VORE2QT7ZDMXOIN7U}
  assets: {favicon-child.ico: YVE3C2Y5DC4MHVAWDB2NCPJT7VRRK53T, standard-page.html: HKRJF6LB43KFECMY2EHX6KGQAHWZZTA7,
    theme.css: N5PBC475YLA5CBDR7PIXU2OGPUXCJZ23, toggle-switch.css: BX6HQ2O43TQJJJHYXZOFBHGFRIQF2VAU,
    toggle-switch.html: QY3AQ2EUH4VVYKUNXSMDXMBJAU6HJ6DK}
