unique_ids:
  forms: {MenuForm: LQALZEBVWCAROGHACHPLSBCRXDO4OOBO, MenuForm.ConnectionsMenu.Connections: LL7KYXL4BXNM3S3HJCAHGVQBOTDUB55K,
    MenuForm.ConnectionsMenu.Groups: ZWOAFHKREOEHY6PHX7SV32EBB4DOCLQQ, MenuForm.DashForm.ProposalRowTemplate: FFDCGOSM4EZON7VB6JSZ2C7OM2MZYMFL,
    MenuForm.MyGroupsForm: VKGIJNVKPA2Q2NNG4HADDOXAPRCDRSDO, MenuForm.WaitForm.TimerForm: 22XNYB3NGYU6HSTKNTX6IJU5WN7U5SQO,
    MenuForm.DashForm: EHZXWVWKJQF4YZIUG5LOWMVHL5UIDUMK, MenuForm.SettingsForm: AKJQZMNZFA4ACJOHUVMORRLHYTTENFCF,
    MenuForm.DashForm.CreateForm.TimeProposalTemplate.HorizontalRule: 3KHHBDA25PB4SUKZLCQVNBFODCLQAT4K,
    LoginForm: U2WRVYCDWTTZ75XOUG5L2YOX2IJKMC57, MenuForm.ConnectionsMenu.Connections.RowTemplate1: 4N2DTNZQ6SNQCDWYT7DBL2C77B4A7UG5,
    MenuForm.MatchForm.MyJitsi: C77GZPNO7ZX3C7KXFKFUX3QCMP4WOHIK, MenuForm.DashForm.CreateForm: FQPF4AUYI6C3RES67N43E3MRNGSYLTGL,
    MenuForm.MatchForm: L6XPKZSV2CGX5N6OQ553T5VUSP75I267, MenuForm.MatchForm.ChatTemplate: CIODZUWNBDQ7GOKRBKNIH5T43Y4UMEM2,
    MenuForm.ConnectionsMenu.Blocks: 5PEZPEX2TVVNEALFCIY2MU7W4RCP27ZX, MenuForm.ConnectionsMenu: N72A3754IWYEWKHSRB56XYWGL2NWXSJX,
    MenuForm.WaitForm: OSIDM6JSG7C65N2DFVSUMY33DDU5IITC, MenuForm.DashForm.CreateForm.TimeProposalTemplate: MAXX7CACIATD6Z3K7F4IENDZVJIT3YS4}
  modules: {helper: TXKYOJQNM66UMMPN27IPCFDOZYFRNLMV, navigation: CQVAOCANKH2QS3QBZ4BEGOJWYCGEDRW2,
    parameters: VS65U2QFLQHWVXRVTTN3IVOMQIHBBRLA}
  server_modules: {matcher: 5A662UJQPLEW6KDDHXY3H72WIVSCH5GQ, server_misc: GEDZ3BUR6ECVXWN2NCI6LBLJMSST3VNN,
    testserver: Q667IDSODZSUAK2QIIGW4U553NIFTFEM}
  assets: {favicon-child.ico: YVE3C2Y5DC4MHVAWDB2NCPJT7VRRK53T, standard-page.html: HKRJF6LB43KFECMY2EHX6KGQAHWZZTA7,
    theme.css: N5PBC475YLA5CBDR7PIXU2OGPUXCJZ23, toggle-switch.css: BX6HQ2O43TQJJJHYXZOFBHGFRIQF2VAU,
    toggle-switch.html: QY3AQ2EUH4VVYKUNXSMDXMBJAU6HJ6DK}
