unique_ids:
  forms: {MenuForm: LQALZEBVWCAROGHACHPLSBCRXDO4OOBO, MenuForm.ConnectionsMenu.Connections: LL7KYXL4BXNM3S3HJCAHGVQBOTDUB55K,
    MenuForm.ConnectionsMenu.Groups: 3RYZNR3XOTRJR2RZ2RTAZLPTCKS4AZZ5, MenuForm.DashForm.ProposalRowTemplate: FFDCGOSM4EZON7VB6JSZ2C7OM2MZYMFL,
    MenuForm.WaitForm.TimerForm: 22XNYB3NGYU6HSTKNTX6IJU5WN7U5SQO, MenuForm.DashForm: EHZXWVWKJQF4YZIUG5LOWMVHL5UIDUMK,
    MenuForm.DashForm.CreateForm.TimeProposalTemplate.HorizontalRule: 3KHHBDA25PB4SUKZLCQVNBFODCLQAT4K,
    LoginForm: U2WRVYCDWTTZ75XOUG5L2YOX2IJKMC57, MenuForm.ConnectionsMenu.Connections.RowTemplate1: 4N2DTNZQ6SNQCDWYT7DBL2C77B4A7UG5,
    MenuForm.MatchForm.MyJitsi: C77GZPNO7ZX3C7KXFKFUX3QCMP4WOHIK, MenuForm.DashForm.CreateForm: FQPF4AUYI6C3RES67N43E3MRNGSYLTGL,
    MenuForm.MatchForm: L6XPKZSV2CGX5N6OQ553T5VUSP75I267, MenuForm.MyGroups: 6YRFJIOMO4PSWRBJIQGBJ6JHFSDRX6LN,
    MenuForm.MatchForm.ChatTemplate: CIODZUWNBDQ7GOKRBKNIH5T43Y4UMEM2, MenuForm.ConnectionsMenu.Blocks: XRHGZYAH3M35WF4X5UGLZK6I2BX36WS3,
    MenuForm.ConnectionsMenu: N72A3754IWYEWKHSRB56XYWGL2NWXSJX, MenuForm.WaitForm: OSIDM6JSG7C65N2DFVSUMY33DDU5IITC,
    MenuForm.DashForm.CreateForm.TimeProposalTemplate: MAXX7CACIATD6Z3K7F4IENDZVJIT3YS4}
  modules: {helper: SGRRVIRQCY5OTROWCBQ65FVMWP5LKAUY, navigation: ELSWCXF2P7WZHQUKOHF2NE4XXKO3KM4K,
    parameters: YGBWKHLDIH257D3HJCDPP5HMLZXGAX7L}
  server_modules: {matcher: W7Z2ZB766VOTHOE3VNOY67R6Z4GVSJ4E, server_misc: JNGPTC2OWLG7LMGMFNF2MPKAHV6LJ5RI,
    testserver: TG5XTHQSVG6CDK4X2GNUQ4NFJM4YJNTX}
  assets: {favicon-child.ico: YVE3C2Y5DC4MHVAWDB2NCPJT7VRRK53T, standard-page.html: HKRJF6LB43KFECMY2EHX6KGQAHWZZTA7,
    theme.css: N5PBC475YLA5CBDR7PIXU2OGPUXCJZ23, toggle-switch.css: BX6HQ2O43TQJJJHYXZOFBHGFRIQF2VAU,
    toggle-switch.html: QY3AQ2EUH4VVYKUNXSMDXMBJAU6HJ6DK}
