unique_ids:
  forms: {MenuForm: LQALZEBVWCAROGHACHPLSBCRXDO4OOBO, MenuForm.ConnectionsMenu.Connections: LL7KYXL4BXNM3S3HJCAHGVQBOTDUB55K,
    MenuForm.DashForm.ProposalRowTemplate: FFDCGOSM4EZON7VB6JSZ2C7OM2MZYMFL, MenuForm.MyGroupsForm: OS7WXWWX7LHOBNF7KXSZ3QYHM75U66U7,
    MenuForm.GroupsMenu.Groups: 3D7EYITMORPXBJPK24O5GTEAX4MWVPER, MenuForm.DashForm: EHZXWVWKJQF4YZIUG5LOWMVHL5UIDUMK,
    MenuForm.SettingsForm: LUQMPWU73DALOFU2FL23UFHAVVTKBLUX, MenuForm.UserMenu: CZGJC7IFQR555IOGNRZW37JZS27KDJ2Z,
    MenuForm.DashForm.TimerForm: 22XNYB3NGYU6HSTKNTX6IJU5WN7U5SQO, LoginForm: U2WRVYCDWTTZ75XOUG5L2YOX2IJKMC57,
    MenuForm.MatchForm.MyJitsi: C77GZPNO7ZX3C7KXFKFUX3QCMP4WOHIK, RowTemplate1: DQ55ZDYXLBMGAM7E5JKPTSNQLNBEM4QP,
    MenuForm.UserMenu.Profile: SCIGZJ3IBCVHDA7N6U4L4T4G57IUU44Y, MenuForm.DashForm.CreateForm: FQPF4AUYI6C3RES67N43E3MRNGSYLTGL,
    MenuForm.GroupsMenu: TGXGMJFSCXXDILI2W2SX47H6V77FYFHS, MenuForm.ConnectionsMenu.Connections.ConnectionRow: 4N2DTNZQ6SNQCDWYT7DBL2C77B4A7UG5,
    MenuForm.MatchForm: L6XPKZSV2CGX5N6OQ553T5VUSP75I267, MenuForm.HorizontalRule: 3KHHBDA25PB4SUKZLCQVNBFODCLQAT4K,
    MenuForm.MatchForm.ChatTemplate: CIODZUWNBDQ7GOKRBKNIH5T43Y4UMEM2, MenuForm.ConnectionsMenu.Blocks: 4V2CC3CY6V7FU27DBZWSDZT5UOMVDXNP,
    MenuForm.ConnectionsMenu: N72A3754IWYEWKHSRB56XYWGL2NWXSJX, MenuForm.UserMenu.History: KKM6BHLTFS2JDFZF3NQSOO5SKC356AXB,
    MenuForm.WaitForm: OSIDM6JSG7C65N2DFVSUMY33DDU5IITC, MenuForm.DashForm.CreateForm.TimeProposalTemplate: MAXX7CACIATD6Z3K7F4IENDZVJIT3YS4,
    MenuForm.GroupsMenu.Members: GYBV3IJB5ANWKRCC4LRIMU33O5ZZ7IPP}
  modules: {helper: B22GXONONXNAFNSHVMP6RMTVPMUS7WAL, parameters: QEXYSHPVRD5JQHPZUUBUVGV6IDOTQW3W,
    rosenberg: LAX53NM7CNDJNS2TRHS5OGADJRIBWEAA, test_now: CY5QVIEWTQK7ZFFFTCFLEVAJ4JYXYXHJ,
    timeproposals: VEPYJRY7V2YGUA44IGDH6SD64URM3UKB}
  server_modules: {matcher: W7L6AF2SOAIOBVHDEMYQSPJP63FLSBB5, server_misc: JRRRPOMXAEI6QJMQOIQUBZN5PKXZLCVB,
    testserver: WNXC4JO5QXE6UA7VORE2QT7ZDMXOIN7U}
  assets: {favicon-child.ico: YVE3C2Y5DC4MHVAWDB2NCPJT7VRRK53T, standard-page.html: HKRJF6LB43KFECMY2EHX6KGQAHWZZTA7,
    theme.css: N5PBC475YLA5CBDR7PIXU2OGPUXCJZ23, toggle-switch.css: BX6HQ2O43TQJJJHYXZOFBHGFRIQF2VAU,
    toggle-switch.html: QY3AQ2EUH4VVYKUNXSMDXMBJAU6HJ6DK}
